development:
  adapter: postgresql
  encoding: unicode
  database: whats_your_constellation_production_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter
#
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: sg_test
#   pool: 5
#   host: localhost
#   port: 5432
#   username: postgres
#   password: carltonlasiter

production:
  adapter: postgresql
  encoding: unicode
  database: whats_your_constellation_production
  pool: 5
  password:
